theme: minima
title: Github Pages Tutorial
author: Michael Flynn
email: mflynn@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This project is to quickly learn how to use Jekyll and Github pages, which 
  are great! This text goes in document head meta for search optimization (?)
  and in the feed.xml site description.


# social links
github_username:  MichaelJFlynn

show_excerpts: true # set to false to remove excerpts on the homepage
